### ISSUE TITLE
Why not read (buffer-list) directly?

### ISSUE THREAD

**Issue by raxod502** [10sr/switch-buffer-functions-el#2]
Another thought I had was, couldn't the previous buffer be determined using

```elisp
(cadr (buffer-list))
```

instead of a variable? That would make the library even simpler.

**Comment by 10sr** [comment]
IMO there is no way to check if current buffer has *actually* been switched without the variable :thinking:

**Comment by raxod502** [comment]
Oh, duh. I was completely misunderstanding this. Sorry.
