### ISSUE TITLE
Can no longer use switch-buffer-functions-el

### ISSUE THREAD

**Issue by vidjuheffex** [10sr/switch-buffer-functions-el#4]
I get a recursive load fatal error that crashes emacs. Deleting the package and reinstalling crashes emacs upon reinstalling. Adding :ensure t to use-package so that it handles the download crashes emacs upon installation.

**Comment by 10sr** [comment]
Sorry for inconvenience, I saw it reproduced.

- Things work when I *updated* it
- The error occurred when I deleted the package once, and reinstalled it

For now I've reverted the change and will look into it, really thanks!

**Comment by vidjuheffex** [comment]
No, thank you, this package is great, really appreciate it.

**Comment by fuyunv** [comment]
This package works as I expect, thank you.
